language: python
python:
  - "3.6"

install:
    - pip install -r requirements.txt

env:
    -DEBUG=True DATABASE_URL="postgres://localhost/test

before_script:
  - psql -c 'create database test;' -U postgres

script: 
  - python app/test_app.py